version: "3.7"
services:
  app:
    build: .
    container_name: ccr_app
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    command: node server.js
